- name: Prepare cloud environment
  hosts: localhost
  gather_facts: False
  roles:
    - { role: clb, when: clb_enabled == 'yes' }
    - { role: servers, when: server_enabled == 'yes' }
    #- { role: cdb, when: cdb_enabled == 'yes' }
